
const players=[
['Nikola Jokić','DEN','C',27.1,12.9,10.2,65.2,98.0],['Shai Gilgeous-Alexander','OKC','G',31.1,5.4,6.8,63.1,97.0],['Luka Dončić','LAL','G',33.5,8.7,8.9,62.4,96.0],['Victor Wembanyama','SAS','C',24.8,11.9,4.3,61.8,95.0],['Giannis Antetokounmpo','MIL','F',29.7,11.5,6.4,65.0,94.0],['Anthony Edwards','MIN','G',28.8,5.6,5.0,58.4,92.0],['Jayson Tatum','BOS','F',27.4,8.9,5.7,60.1,91.0],['Kevin Durant','HOU','F',25.8,6.2,4.8,64.0,90.0],['Stephen Curry','GSW','G',26.7,4.5,6.1,63.8,89.0],['Donovan Mitchell','CLE','G',27.1,5.0,5.8,59.9,88.0],['Bam Adebayo','MIA','C',23.4,9.8,4.6,62.0,87.0],['De\'Aaron Fox','SAS','G',24.9,4.2,6.8,57.9,86.0],['Jaylen Brown','PHI','F',28.7,6.4,4.9,59.3,85.0],['Karl-Anthony Towns','NYK','C',22.8,11.9,3.1,64.7,84.0],['Jalen Brunson','NYK','G',27.9,3.1,7.4,58.8,83.0],['Cade Cunningham','DET','G',26.1,6.1,9.3,56.9,82.0],['Paolo Banchero','ORL','F',23.9,8.1,5.1,57.2,81.0],['Tyrese Haliburton','IND','G',18.2,3.7,10.6,60.4,80.0],['LeBron James','PHI','F',23.6,6.8,7.9,61.2,79.0],['Chet Holmgren','OKC','C',19.7,9.1,2.9,64.3,78.0],['Alperen Şengün','HOU','C',20.8,10.4,5.1,59.8,77.0],['Jalen Williams','OKC','F',23.1,5.9,5.4,61.1,76.0],['Franz Wagner','ORL','F',24.1,5.8,4.8,59.7,75.0],['Scottie Barnes','TOR','F',19.4,7.8,6.2,55.8,74.0],['Evan Mobley','CLE','C',17.8,9.5,3.6,62.2,73.0]];
const goat=[['Michael Jordan','CHI','984.7'],['LeBron James','CLE / MIA / LAL','979.8'],['Nikola Jokić','DEN','971.9'],['Kareem Abdul-Jabbar','MIL / LAL','967.4'],['Bill Russell','BOS','963.8'],['Tim Duncan','SAS','958.6'],['Magic Johnson','LAL','955.2'],['Larry Bird','BOS','953.9'],['Stephen Curry','GSW','949.7'],["Shaquille O'Neal",'ORL / LAL / MIA','947.8']];
const season=players.map((p,i)=>[p[0],p[2],p[3],p[4],p[5],p[6],Math.max(68,98-i*1.1)]);
const defaults={headline:'NBA\nразобранная\nпо цифрам.',intro:'COURTSIDE объединяет статистику NBA, аналитические рейтинги, прогнозы и GI в один цифровой баскетбольный альбом.',mvp:'Nikola Jokić',dpoy:'Victor Wembanyama',roy:'Cam Boozer',mip:'Stephon Castle',forecastText:'Наша задача не угадать будущее, а ясно показать, почему этот прогноз имеет смысл.',giText:'GI оценивает влияние игрока через пик, стабильность, контекст и плей-офф.'};
function data(){try{return {...defaults,...JSON.parse(localStorage.getItem('courtsideData')||'{}')}}catch{return defaults}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(active){document.querySelectorAll('.links a').forEach(a=>{if(a.dataset.page===active)a.classList.add('active')})}
function renderTable(id, arr){const el=document.getElementById(id); if(!el)return; el.innerHTML=arr.map((p,i)=>`<tr><td>${i+1}</td><td><b>${esc(p[0])}</b></td><td>${p[1]}</td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td>${p[5]}%</td><td class="score">${p[6]}</td></tr>`).join('')}
function initStats(){let arr=[...players];const search=document.getElementById('search'),sort=document.getElementById('sort'),pos=document.getElementById('pos');function draw(){let q=(search.value||'').toLowerCase(),p=pos.value,s=sort.value,idx={gi:7,pts:3,reb:4,ast:5,ts:6}[s];let a=arr.filter(x=>x[0].toLowerCase().includes(q)&&(p==='all'||x[2]===p)).sort((a,b)=>b[idx]-a[idx]);renderTable('statsBody',a.map(x=>[x[0],x[1],x[3],x[4],x[5],x[6],x[7]]));}search.oninput=sort.onchange=pos.onchange=draw;draw()}
function initGI(){const el=document.getElementById('giBody'); if(!el)return;el.innerHTML=season.map((p,i)=>`<tr><td>${i+1}</td><td><b>${esc(p[0])}</b></td><td>${p[1]}</td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td>${p[5]}%</td><td class="score">${p[6].toFixed(1)}</td></tr>`).join('')}
function initGoat(){const el=document.getElementById('goatBody');if(!el)return;el.innerHTML=goat.map((p,i)=>`<div class="row"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="player">${esc(p[0])}<span class="team">${p[1]}</span></span><span class="score">${p[2]}</span></div>`).join('')}
function initHome(){const d=data();const h=document.getElementById('headline'), intro=document.getElementById('intro');if(h)h.innerHTML=esc(d.headline).replace(/\\n|\n/g,'<br>');if(intro)intro.textContent=d.intro;}
function initForecast(){const d=data();for(const id of ['mvp','dpoy','roy','mip','forecastText']){const el=document.getElementById(id);if(el)el.textContent=d[id]}}
function initEditor(){const d=data();for(const k of Object.keys(defaults)){const el=document.getElementById('e_'+k);if(el)el.value=d[k]}document.getElementById('save').onclick=()=>{const n={};for(const k of Object.keys(defaults)){const el=document.getElementById('e_'+k);n[k]=el?el.value:d[k]}localStorage.setItem('courtsideData',JSON.stringify(n));document.getElementById('saved').textContent='Сохранено в этом браузере. Обновите другие страницы.';};document.getElementById('reset').onclick=()=>{localStorage.removeItem('courtsideData');location.reload()}}
